import type {Metadata} from "next";
import {Providers} from "@/app/_providers/Providers";
import {Navbar} from "@/app/components";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="es">
      <body>
      <Providers>
        <Navbar/>
        {children}
      </Providers>
      </body>
      </html>
  );
}
